### ISSUE TITLE
Option to pin a package to a version and only display if there is a new fix release

### ISSUE THREAD

**Issue by cleder** [bartTC/pip-check#11]
e.g. django has a LTS version 1.8, I'd like to stay on 1.8.x, but I need to know if there is a new bugfix release 1.8.y (y>x)

**Comment by bartTC** [comment]
I first thought this is a good idea but ... it might make things too complicated, and contradicts the purpose. But version 2 now uses `pip` itself to retrieve the package status, and pip knows the 'up most' dependency of all packages. 

E.g. for me in one particular venv it displays Django 1.11 as the 'latest' version because another requirement (django-cms) is not yet 2.0 compatible:

```
┌─────────────────────────┬─────────┬─────────┬──────────────────────────────────────────────────────┐
│ Minor Release Update    │ Version │ Latest  │                                                      │
├─────────────────────────┼─────────┼─────────┼──────────────────────────────────────────────────────┤
│ Django                  │ 1.10.8  │ 1.11.10 │ https://pypi.python.org/pypi/Django                  │
```

Another venv with Python3 tells me 2.0 is the latest:

```
┌──────────────────────┬─────────────┬───────────┬─────────────────────────────────────────────────┐
│ Major Release Update │ Version     │ Latest    │                                                 │
├──────────────────────┼─────────────┼───────────┼─────────────────────────────────────────────────┤
│ certifi              │ 2017.7.27.1 │ 2018.1.18 │ https://pypi.python.org/pypi/certifi            │
│ Django               │ 1.11.1      │ 2.0.2     │ https://pypi.python.org/pypi/Django             │
```

I think this behavior is close(r) to your expectations.
